### ISSUE TITLE
'allocate_port_range' causing a crash

### ISSUE THREAD

**Issue by jonpwilson** [bbc/hive-runner#121]
The config was allocating 50 ports per worker so not sure why it should have run out of ports:
```
/home/hive/.rvm/gems/ruby-2.3.0/gems/hive-runner-2.1.0/lib/hive/port_allocator.rb:52:in `allocate_port_range': Hive::PortAllocator::NoPortsAvailable (Hive::PortAllocator::NoPortsAvailable)
        from /home/hive/.rvm/gems/ruby-2.3.0/gems/hive-runner-2.1.0/lib/hive/register.rb:67:in `block (2 levels) in check_controllers'
        from /home/hive/.rvm/gems/ruby-2.3.0/gems/hive-runner-2.1.0/lib/hive/register.rb:60:in `each'
        from /home/hive/.rvm/gems/ruby-2.3.0/gems/hive-runner-2.1.0/lib/hive/register.rb:60:in `block in check_controllers'
        from /home/hive/.rvm/gems/ruby-2.3.0/gems/hive-runner-2.1.0/lib/hive/register.rb:55:in `each'
        from /home/hive/.rvm/gems/ruby-2.3.0/gems/hive-runner-2.1.0/lib/hive/register.rb:55:in `check_controllers'
        from /home/hive/.rvm/gems/ruby-2.3.0/gems/hive-runner-2.1.0/lib/hive/register.rb:47:in `block in run'
        from /home/hive/.rvm/gems/ruby-2.3.0/gems/hive-runner-2.1.0/lib/hive/register.rb:44:in `loop'
        from /home/hive/.rvm/gems/ruby-2.3.0/gems/hive-runner-2.1.0/lib/hive/register.rb:44:in `run'
        from /home/hive/.rvm/gems/ruby-2.3.0/gems/hive-runner-2.1.0/bin/start_hive:120:in `<top (required)>'
        from /home/hive/.rvm/gems/ruby-2.3.0/gems/daemons-1.2.3/lib/daemons/application.rb:218:in `load'
        from /home/hive/.rvm/gems/ruby-2.3.0/gems/daemons-1.2.3/lib/daemons/application.rb:218:in `start_load'
        from /home/hive/.rvm/gems/ruby-2.3.0/gems/daemons-1.2.3/lib/daemons/application.rb:297:in `start'
        from /home/hive/.rvm/gems/ruby-2.3.0/gems/daemons-1.2.3/lib/daemons/controller.rb:56:in `run'
        from /home/hive/.rvm/gems/ruby-2.3.0/gems/daemons-1.2.3/lib/daemons.rb:144:in `block in run'
        from /home/hive/.rvm/gems/ruby-2.3.0/gems/daemons-1.2.3/lib/daemons/cmdline.rb:88:in `catch_exceptions'
        from /home/hive/.rvm/gems/ruby-2.3.0/gems/daemons-1.2.3/lib/daemons.rb:143:in `run'
        from /home/hive/.rvm/gems/ruby-2.3.0/gems/hive-runner-2.1.0/bin/hived:31:in `<top (required)>'
        from /home/hive/.rvm/gems/ruby-2.3.0/bin/hived:23:in `load'
        from /home/hive/.rvm/gems/ruby-2.3.0/bin/hived:23:in `<main>'
        from /home/hive/.rvm/gems/ruby-2.3.0/bin/ruby_executable_hooks:15:in `eval'
        from /home/hive/.rvm/gems/ruby-2.3.0/bin/ruby_executable_hooks:15:in `<main>'
```

**Comment by jonpwilson** [comment]
This issue hasn't presented itself again in the last 4 months.
